### ISSUE TITLE
flownetf and flownetb

### ISSUE THREAD

**Issue by xieyipeng** [csyxwei/FFWM#12]
could you provide the pretrained flownetf and flownetb model?
Thank you very much！

**Comment by csyxwei** [comment]
Hi, 

You can download the pretrained flownetf model from [GoogleDrive](https://drive.google.com/drive/folders/1U26FvuLtXraxPrRNxCxFka3DOvRuG4NW?usp=sharing) or [BaiduNetDisk](https://pan.baidu.com/s/1X62Atd9Q_USs0aGQk3WllA) (l98p). Since the flownetb model was not used in the inference, I didn't save its model on my computer.
