### ISSUE TITLE
Possible alternative version without any CUDA extensions

### ISSUE THREAD

**Issue by xsacha** [csyxwei/FFWM#4]
Is it possible to make a version that does not rely on CUDA extensions so that we can perform conversions, change dtype, change device and other such torch modifications?

**Comment by csyxwei** [comment]
Hi, 

For training, it may be not. Because some training losses require the customed CUDA extensions (i.e., PerceptualCorrectness and MultiAffineRegularizationLoss for training flownet). Or you can replace these losses with other similar losses to remove the customed CUDA extensions.

For testing, it is possible. You can replace the .cuda() in external_function.py ffwm_model.py flownet_model.py  and losses.py with .to(self.device) or .type_as(xxx). Then you can use --gpu_ids to set GPU or CPU. I will release this version code soon.

**Comment by csyxwei** [comment]
I have updated the code to support the cpu testing. You can use `--gpu_ids -1` to test it.  For training the flownet, GPU is also needed.

**Comment by xsacha** [comment]
Thanks
